import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Accordion from "@/components/accordion";
import { Fragment } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Diverse group generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-screen-lg mx-auto">
        <h1 className="font-sans font-light text-3xl text-gray-600 mx-auto text-center sm:text-left py-5 px-2">
          Diverse group generator
        </h1>
        <Accordion title="1. Register members to be grouped">
          <div>My name</div>
        </Accordion>
        <Accordion title="2. Grouping setup">
          <div>My name</div>
        </Accordion>
      </div>
    </>
  );
}
